/**
 * 12 NONCLINICAL Demonstration Questions
 * 
 * IMPORTANT CONTENT HONESTY NOTICE:
 * These questions are strictly demonstration items designed to exercise the software,
 * test biostatistics logic, data interpretation, cognitive reasoning, and app mechanics.
 * They DO NOT contain clinical advice, real patient data, or official USMLE exam content.
 * All taxonomies are marked with "(Demo)".
 */

import type { Question } from '../domain/types';

export const DEMO_QUESTIONS: Question[] = [
  {
    id: 'demo-001',
    version: 1,
    contentKind: 'demo',
    exam: 'USMLE Step 1 (Demo Taxonomy)',
    system: 'Demo - Biostatistics & Trial Design',
    discipline: 'Demo - Epidemiology',
    topic: 'Sensitivity & Specificity Trade-offs',
    learningObjective: 'Understand how shifting a diagnostic biomarker cut-off point influences false-positive and false-negative rates.',
    vignette: 'A research team is calibrating a novel automated assay for Fictional Biomarker X (measured in ng/mL) to screen an asymptomatic population. At the current cutoff of 50 ng/mL, the assay has a sensitivity of 88% and a specificity of 85%. The investigators decide to lower the diagnostic threshold from 50 ng/mL to 35 ng/mL to avoid missing individuals with early biochemical elevation.\n\nWhich of the following changes in diagnostic parameters is most likely to occur as a direct consequence of lowering this threshold?',
    options: [
      { id: 'A', text: 'Sensitivity increases and false-positive rate increases' },
      { id: 'B', text: 'Sensitivity decreases and negative predictive value decreases' },
      { id: 'C', text: 'Specificity increases and positive predictive value increases' },
      { id: 'D', text: 'False-negative rate increases and specificity decreases' },
      { id: 'E', text: 'Both sensitivity and specificity increase simultaneously' },
    ],
    correctOptionId: 'A',
    explanation: 'Lowering the diagnostic cutoff threshold makes the test more lenient (more tests are declared positive). Consequently, more true positives are captured (sensitivity increases), but more disease-free individuals are mistakenly classified as positive (false positives increase, and specificity decreases).',
    optionExplanations: {
      A: 'Correct. Lowering the cutoff criterion classifies more values as positive, capturing borderline true cases (increasing sensitivity) while inevitably sweeping in healthy outliers (increasing false positives and lowering specificity).',
      B: 'Incorrect. Sensitivity increases when the threshold is lowered, and negative predictive value (NPV) typically increases because fewer false negatives occur.',
      C: 'Incorrect. Specificity decreases because more healthy individuals will exceed the lowered threshold, increasing false positives.',
      D: 'Incorrect. The false-negative rate decreases (1 - Sensitivity), not increases.',
      E: 'Incorrect. For a single test metric with overlapping distributions, shifting the cut-off point moves along the Receiver Operating Characteristic (ROC) curve; sensitivity and specificity exhibit an inverse trade-off.',
    },
    keyTakeaway: 'Lowering a test threshold catches more true cases (higher sensitivity) at the expense of more false alarms (lower specificity).',
    authorDifficulty: 'Medium',
    editorialStatus: 'Demo Reviewed',
    reviewer: { name: null, role: null },
    references: ['Gordis Epidemiology, 6th Ed. (Principles of Screening)', 'Fletcher Clinical Epidemiology'],
  },
  {
    id: 'demo-002',
    version: 1,
    contentKind: 'demo',
    exam: 'USMLE Step 1 (Demo Taxonomy)',
    system: 'Demo - Biostatistics & Trial Design',
    discipline: 'Demo - Clinical Trials',
    topic: 'Intention-to-Treat (ITT) Analysis',
    learningObjective: 'Recognize the fundamental purpose and method of Intention-to-Treat (ITT) analysis in randomized controlled trials.',
    vignette: 'In a double-blind, randomized controlled trial comparing a hypothetical oral compound (Compound Alpha) with placebo over 12 months, 500 participants are randomized to each group. At month 6, 40 participants in the active treatment arm discontinue the compound due to benign gastrointestinal discomfort, and 15 participants in the placebo group drop out due to relocation.\n\nWhen evaluating the primary efficacy endpoint at 12 months, which analytic strategy best preserves baseline randomization and minimizes attrition bias?',
    options: [
      { id: 'A', text: 'Per-protocol analysis including only participants who completed all 12 months with >90% compliance' },
      { id: 'B', text: 'Intention-to-treat analysis analysing all randomized participants according to their original group assignment' },
      { id: 'C', text: 'As-treated analysis grouping subjects based on the total cumulative dose actually ingested' },
      { id: 'D', text: 'Subgroup analysis excluding all participants who developed adverse drug events' },
      { id: 'E', text: 'Cross-over reassignment of non-compliant subjects into the placebo cohort' },
    ],
    correctOptionId: 'B',
    explanation: 'Intention-to-treat (ITT) analysis preserves the benefits of randomization by including all randomized participants in the group they were originally assigned to, regardless of adherence, withdrawal, or protocol deviations. This prevents attrition bias.',
    optionExplanations: {
      A: 'Incorrect. Per-protocol analysis excludes dropouts and non-compliant subjects, which breaks randomization and can falsely inflate efficacy.',
      B: 'Correct. ITT analyzes all subjects according to initial random allocation, preserving prognostic balance between study arms and reflecting real-world effectiveness.',
      C: 'Incorrect. As-treated analysis violates randomization and introduces confounding by indication or compliance characteristics.',
      D: 'Incorrect. Excluding patients with adverse events causes selective attrition bias.',
      E: 'Incorrect. Reassigning non-compliant patients destroys the randomized allocation completely.',
    },
    keyTakeaway: 'Intention-to-treat analysis preserves randomization and prevents bias caused by selective dropout.',
    authorDifficulty: 'Easy',
    editorialStatus: 'Demo Reviewed',
    reviewer: { name: null, role: null },
    references: ['Consolidated Standards of Reporting Trials (CONSORT guidelines)'],
  },
  {
    id: 'demo-003',
    version: 1,
    contentKind: 'demo',
    exam: 'USMLE Step 1 (Demo Taxonomy)',
    system: 'Demo - Behavioral Sciences & Ethics',
    discipline: 'Demo - Cognitive Psychology',
    topic: 'Cognitive Biases in Diagnostic Reasoning',
    learningObjective: 'Identify and differentiate cognitive biases, specifically anchoring bias and premature closure.',
    vignette: 'A fictional resident physician in a simulation lab assesses an electronic simulated chart. The patient is flagged on admission as "suspected community-acquired bronchitis" based on triage notes. During the physical exam simulator, new findings of asymmetric lower extremity swelling, dullness to percussion at the right lung base, and tachypnea are revealed. The resident orders repeated cough suppressants and inhaled bronchodilators without ordering thoracic imaging or considering pulmonary thromboembolism.\n\nWhich cognitive heuristic or bias is most prominently demonstrated by the resident’s decision-making process?',
    options: [
      { id: 'A', text: 'Availability heuristic' },
      { id: 'B', text: 'Anchoring bias (premature closure)' },
      { id: 'C', text: 'Hindsight bias' },
      { id: 'D', text: 'Framing effect' },
      { id: 'E', text: 'Blind-spot bias' },
    ],
    correctOptionId: 'B',
    explanation: 'Anchoring bias occurs when a clinician fixates on initial information (the triage diagnosis of "bronchitis") and fails to adjust their diagnostic impressions despite discordant subsequent clinical cues (asymmetric leg swelling and focal chest findings). This frequently leads to premature closure.',
    optionExplanations: {
      A: 'Incorrect. Availability heuristic involves judging the probability of an event based on how easily recent or memorable examples come to mind.',
      B: 'Correct. Anchoring bias involves clinging to initial impressions (anchors) and failing to reconsider alternative hypotheses in light of new conflicting data.',
      C: 'Incorrect. Hindsight bias is the tendency to view past events as having been predictable once the outcome is already known ("I knew it all along").',
      D: 'Incorrect. Framing effect occurs when choices are influenced by whether options are presented as potential gains or losses.',
      E: 'Incorrect. Blind-spot bias is recognizing bias in other individuals while failing to see one’s own biases.',
    },
    keyTakeaway: 'Anchoring bias leads clinicians to anchor on early impressions and dismiss subsequent contradictory clinical clues.',
    authorDifficulty: 'Medium',
    editorialStatus: 'Demo Reviewed',
    reviewer: { name: null, role: null },
    references: ['Croskerry P. Cognitive forcing strategies in clinical decision making.'],
  },
  {
    id: 'demo-004',
    version: 1,
    contentKind: 'demo',
    exam: 'USMLE Step 1 (Demo Taxonomy)',
    system: 'Demo - Cardiovascular Logic',
    discipline: 'Demo - Hemodynamics',
    topic: 'Pressure-Volume Loop Logic',
    learningObjective: 'Deduce the hemodynamic consequences of increasing systemic vascular resistance on ventricular pressure-volume loops.',
    vignette: 'In an isolated organ bath simulation of left ventricular mechanics, a synthetic vasoconstrictor is infused into the outflow tract to simulate a sudden 40% increase in systemic vascular resistance (afterload), while keeping myocardial contractility and heart rate constant.\n\nAssuming venous return remains momentarily unchanged, which of the following changes in the left ventricular pressure-volume loop will be observed on the subsequent cardiac cycle?',
    options: [
      { id: 'A', text: 'Increased end-systolic volume and decreased stroke volume' },
      { id: 'B', text: 'Decreased peak systolic pressure and increased stroke volume' },
      { id: 'C', text: 'Decreased end-systolic volume and increased ejection fraction' },
      { id: 'D', text: 'Increased stroke volume with unaffected end-systolic pressure' },
      { id: 'E', text: 'Decreased end-diastolic volume with widened loop width' },
    ],
    correctOptionId: 'A',
    explanation: 'An acute increase in afterload forces the left ventricle to contract against greater resistance. Ejection is impeded, leading to higher peak systolic pressure, earlier closure of the aortic valve, higher end-systolic volume (ESV), and narrower loop width (decreased stroke volume = EDV - ESV).',
    optionExplanations: {
      A: 'Correct. Higher afterload increases the pressure the ventricle must generate to open the aortic valve and impedes shortening, leaving more residual blood in the chamber at end-systole (higher ESV), thus reducing stroke volume.',
      B: 'Incorrect. Peak systolic pressure rises with increased afterload, while stroke volume falls.',
      C: 'Incorrect. End-systolic volume increases, so ejection fraction (SV/EDV) decreases.',
      D: 'Incorrect. Stroke volume decreases, not increases.',
      E: 'Incorrect. Stroke volume is the horizontal width of the PV loop; increased afterload narrows the loop width.',
    },
    keyTakeaway: 'Elevated afterload shifts the end-systolic point upward and to the right, increasing ESV and decreasing stroke volume.',
    authorDifficulty: 'Hard',
    editorialStatus: 'Demo Reviewed',
    reviewer: { name: null, role: null },
    references: ['Katz AM. Physiology of the Heart. Circulation Review.'],
  },
  {
    id: 'demo-005',
    version: 1,
    contentKind: 'demo',
    exam: 'USMLE Step 1 (Demo Taxonomy)',
    system: 'Demo - Respiratory Logic',
    discipline: 'Demo - Pulmonary Physiology',
    topic: 'Ventilation-Perfusion (V/Q) Mismatch Reasoning',
    learningObjective: 'Analyze the physiological response to a pure right-to-left anatomical shunt versus an area of low V/Q mismatch.',
    vignette: 'Two experimental models of arterial hypoxemia are simulated in a computer bench test:\n- Model 1 represents diffuse alveolar airway narrowing with a reduced ventilation-to-perfusion ratio (low V/Q area).\n- Model 2 represents complete anatomical right-to-left intracardiac shunting (V/Q = 0).\n\nBoth models are administered 100% inspired supplemental oxygen (FiO2 = 1.0).\n\nWhich of the following outcomes will be observed regarding arterial oxygen tension (PaO2)?',
    options: [
      { id: 'A', text: 'Model 1 shows substantial improvement in PaO2, while Model 2 shows minimal or no improvement' },
      { id: 'B', text: 'Model 2 shows substantial improvement in PaO2, while Model 1 shows minimal or no improvement' },
      { id: 'C', text: 'Neither model responds to 100% supplemental oxygen' },
      { id: 'D', text: 'Both models normalize their alveolar-arterial (A-a) gradient to zero' },
      { id: 'E', text: 'Model 1 develops hypercapnia while Model 2 develops hypocapnia' },
    ],
    correctOptionId: 'A',
    explanation: 'Hypoxemia caused by low V/Q mismatch improves dramatically with high FiO2 because oxygen-enriched gas enters poorly ventilated but still patent alveoli, raising the oxygen content of end-capillary blood. In contrast, true right-to-left shunt blood bypasses ventilated alveoli entirely, so 100% FiO2 cannot oxygenate that shunted fraction, yielding minimal PaO2 increase.',
    optionExplanations: {
      A: 'Correct. Low V/Q regions respond to supplemental oxygen because the oxygenated alveolar gas reaches the blood. Pure shunts fail to respond because shunted blood never contacts alveolar gas.',
      B: 'Incorrect. Shunts are notoriously refractory to 100% FiO2.',
      C: 'Incorrect. Low V/Q mismatch does respond to supplemental oxygen.',
      D: 'Incorrect. The A-a gradient remains elevated in both conditions, and 100% FiO2 markedly widens the calculated A-a gradient.',
      E: 'Incorrect. PaO2 response is the definitive differentiator, not a reciprocal change in carbon dioxide.',
    },
    keyTakeaway: 'Hypoxemia from low V/Q mismatch corrects with 100% oxygen; hypoxemia from a true right-to-left shunt does not.',
    authorDifficulty: 'Medium',
    editorialStatus: 'Demo Reviewed',
    reviewer: { name: null, role: null },
    references: ['West JB. Respiratory Physiology: The Essentials.'],
  },
  {
    id: 'demo-006',
    version: 1,
    contentKind: 'demo',
    exam: 'USMLE Step 1 (Demo Taxonomy)',
    system: 'Demo - Renal & Acid-Base Logic',
    discipline: 'Demo - Acid-Base Physiology',
    topic: 'Anion Gap & Winter’s Formula Logic',
    learningObjective: 'Apply Winter’s formula to determine appropriate respiratory compensation in high anion gap metabolic acidosis.',
    vignette: 'An arterial blood gas (ABG) simulation engine outputs the following values for a hypothetical scenario:\n- pH: 7.25\n- Serum Na+: 140 mEq/L\n- Serum Cl-: 98 mEq/L\n- Serum HCO3-: 14 mEq/L\n- PaCO2: 29 mm Hg\n\nWinter’s formula states that expected PaCO2 = (1.5 × [HCO3-]) + 8 ± 2.\n\nWhich of the following acid-base interpretations is most accurate based on these simulated parameters?',
    options: [
      { id: 'A', text: 'High anion gap metabolic acidosis with appropriate respiratory compensation' },
      { id: 'B', text: 'High anion gap metabolic acidosis with concomitant respiratory alkalosis' },
      { id: 'C', text: 'Normal anion gap metabolic acidosis with concomitant respiratory acidosis' },
      { id: 'D', text: 'Primary respiratory acidosis with secondary renal bicarbonate wasting' },
      { id: 'E', text: 'Mixed metabolic alkalosis and metabolic acidosis without respiratory participation' },
    ],
    correctOptionId: 'A',
    explanation: '1) Anion gap = Na+ - (Cl- + HCO3-) = 140 - (98 + 14) = 28 mEq/L (normal is 8-12 mEq/L), indicating a High Anion Gap Metabolic Acidosis (HAGMA).\n2) Expected PaCO2 by Winter’s formula: (1.5 × 14) + 8 ± 2 = 21 + 8 ± 2 = 29 ± 2 mm Hg (range 27–31 mm Hg).\n3) The measured PaCO2 is 29 mm Hg, falling precisely in the expected range. Therefore, respiratory compensation is appropriate.',
    optionExplanations: {
      A: 'Correct. The anion gap is 28 (elevated), and measured PaCO2 (29 mm Hg) matches the predicted compensatory range (27-31 mm Hg).',
      B: 'Incorrect. If PaCO2 were lower than 27 mm Hg, a concomitant respiratory alkalosis would be diagnosed.',
      C: 'Incorrect. Anion gap is markedly elevated (28), and PaCO2 is not above 31 mm Hg.',
      D: 'Incorrect. Primary process is metabolic acidosis with low pH and low bicarbonate.',
      E: 'Incorrect. This ignores both the severe anion gap and the ventilatory compensation.',
    },
    keyTakeaway: 'In metabolic acidosis, calculate the anion gap, then use Winter’s formula to verify whether respiratory compensation is adequate.',
    authorDifficulty: 'Medium',
    editorialStatus: 'Demo Reviewed',
    reviewer: { name: null, role: null },
    references: ['Rose & Post. Clinical Physiology of Acid-Base and Electrolyte Disorders.'],
  },
  {
    id: 'demo-007',
    version: 1,
    contentKind: 'demo',
    exam: 'USMLE Step 1 (Demo Taxonomy)',
    system: 'Demo - Pharmacokinetics',
    discipline: 'Demo - Pharmacology',
    topic: 'Loading Dose & Volume of Distribution',
    learningObjective: 'Calculate loading dose requirements based on target plasma concentration and volume of distribution.',
    vignette: 'A pharmacokinetic model is programmed for a hypothetical synthetic antimicrobial, Drug Theta. The parameters are:\n- Target peak plasma concentration (Cp): 12 mg/L\n- Apparent Volume of Distribution (Vd): 0.5 L/kg\n- Bioavailability (F): 1.0 (intravenous formulation)\n- Clearance (CL): 0.05 L/hr/kg\n\nFor a simulated adult patient weighing 70 kg, what is the required intravenous loading dose (LD) to immediately achieve the target peak plasma concentration?',
    options: [
      { id: 'A', text: '420 mg' },
      { id: 'B', text: '840 mg' },
      { id: 'C', text: '210 mg' },
      { id: 'D', text: '600 mg' },
      { id: 'E', text: '42 mg' },
    ],
    correctOptionId: 'A',
    explanation: 'The loading dose formula is: Loading Dose = (Target Cp × Total Vd) / F.\n1) Total Vd = 0.5 L/kg × 70 kg = 35 Liters.\n2) Loading Dose = (12 mg/L × 35 L) / 1.0 = 420 mg.',
    optionExplanations: {
      A: 'Correct. Loading Dose = (Cp × Vd) / F = (12 mg/L × 35 L) / 1.0 = 420 mg.',
      B: 'Incorrect. 840 mg would result if Vd were mistakenly taken as 1.0 L/kg.',
      C: 'Incorrect. 210 mg is half of the required dose, perhaps confusing maintenance dose clearance.',
      D: 'Incorrect. Arithmetic miscalculation.',
      E: 'Incorrect. Off by an order of magnitude due to incorrect unit conversion.',
    },
    keyTakeaway: 'Loading dose depends on the target plasma concentration and volume of distribution (LD = Cp × Vd / F), independent of clearance.',
    authorDifficulty: 'Easy',
    editorialStatus: 'Demo Reviewed',
    reviewer: { name: null, role: null },
    references: ['Katzung Basic & Clinical Pharmacology, 15th Ed.'],
  },
  {
    id: 'demo-008',
    version: 1,
    contentKind: 'demo',
    exam: 'USMLE Step 1 (Demo Taxonomy)',
    system: 'Demo - Genetics & Molecular Logic',
    discipline: 'Demo - Molecular Genetics',
    topic: 'Hardy-Weinberg Equilibrium Logic',
    learningObjective: 'Calculate carrier frequency for an autosomal recessive trait under Hardy-Weinberg equilibrium assumptions.',
    vignette: 'In a fictional isolated population simulation, an autosomal recessive enzyme deficiency has a measured disease prevalence of 1 in 2,500 live births (q² = 1/2500). The simulation assumes standard Hardy-Weinberg equilibrium conditions (no selection, random mating, large population size, no migration, and negligible mutation rate).\n\nWhat is the approximate carrier frequency (2pq) of this gene variant in this simulated population?',
    options: [
      { id: 'A', text: '1 in 26 (approximately 3.9%)' },
      { id: 'B', text: '1 in 50 (approximately 2.0%)' },
      { id: 'C', text: '1 in 100 (approximately 1.0%)' },
      { id: 'D', text: '1 in 500 (approximately 0.2%)' },
      { id: 'E', text: '1 in 1,250 (approximately 0.08%)' },
    ],
    correctOptionId: 'A',
    explanation: '1) Disease frequency = q² = 1/2500, therefore the mutant allele frequency q = √(1/2500) = 1/50 = 0.02.\n2) The normal allele frequency p = 1 - q = 1 - 0.02 = 0.98 (approximately 1.0).\n3) The carrier frequency = 2pq = 2 × 0.98 × 0.02 = 0.0392 = 3.92%, which is 1 in (1 / 0.0392) ≈ 1 in 25.5 (~1 in 26).',
    optionExplanations: {
      A: 'Correct. q = 1/50 = 0.02; p ≈ 0.98; carrier frequency 2pq ≈ 2 × (1) × (1/50) = 2/50 = 1/25.5 ≈ 1 in 26.',
      B: 'Incorrect. 1 in 50 (0.02) represents the allele frequency q, not the diploid heterozygote frequency 2pq.',
      C: 'Incorrect. Overlooks the factor of 2 in the 2pq binomial expansion.',
      D: 'Incorrect. Mathematical division error.',
      E: 'Incorrect. Represents half of the disease frequency rather than the carrier frequency.',
    },
    keyTakeaway: 'For rare autosomal recessive conditions, the mutant allele frequency q = √(prevalence), and carrier frequency 2pq ≈ 2q.',
    authorDifficulty: 'Medium',
    editorialStatus: 'Demo Reviewed',
    reviewer: { name: null, role: null },
    references: ['Nussbaum RL. Thompson & Thompson Genetics in Medicine.'],
  },
  {
    id: 'demo-009',
    version: 1,
    contentKind: 'demo',
    exam: 'USMLE Step 1 (Demo Taxonomy)',
    system: 'Demo - Study Strategy & Metacognition',
    discipline: 'Demo - Learning Science',
    topic: 'Spaced Retrieval vs Passive Rereading',
    learningObjective: 'Analyze the evidence-based cognitive mechanisms underlying the testing effect and spaced repetition for board preparation.',
    vignette: 'Two groups of adult medical learners prepare for a comprehensive examination over an 8-week block:\n- Group 1 spends 20 hours passively reviewing annotated lecture slides and re-highlighting textbook outlines.\n- Group 2 spends 12 hours actively answering mixed-topic practice questions with detailed review of rationales, plus 4 hours of flashcard spaced retrieval.\n\nAccording to cognitive psychology literature on memory consolidation (Roediger & Karpicke, Bjork’s desirable difficulties), which outcome will Group 2 most reliably demonstrate on delayed retention testing at 6 months?',
    options: [
      { id: 'A', text: 'Superior delayed concept recall and enhanced transfer of knowledge to unfamiliar clinical vignettes' },
      { id: 'B', text: 'Lower retrieval strength due to cognitive fatigue from frequent self-assessment' },
      { id: 'C', text: 'Equivalent long-term retention but with higher subjective illusion of competence' },
      { id: 'D', text: 'Faster initial reading speed with impaired synthesis of multi-step pathophysiological mechanisms' },
      { id: 'E', text: 'Higher rote verbatim memorization but inferior semantic schema formation' },
    ],
    correctOptionId: 'A',
    explanation: 'Active retrieval practice (testing effect) forces neural reconstruction of memory traces, which significantly strengthens synaptic pathways and promotes mental schema formation compared to passive rereading. This results in superior delayed retention and better transfer to novel problems.',
    optionExplanations: {
      A: 'Correct. Retrieval practice creates "desirable difficulties" that produce durable memory traces and flexible conceptual transfer.',
      B: 'Incorrect. Retrieval practice enhances retrieval strength and storage strength over time.',
      C: 'Incorrect. Passive rereading creates the "illusion of competence" (fluency heuristic), whereas active testing accurately calibrates self-awareness.',
      D: 'Incorrect. Group 2 engages in deeper semantic synthesis, not superficial reading speed.',
      E: 'Incorrect. Spaced testing strengthens semantic networks, whereas passive rereading tends to produce fragile verbatim familiarity.',
    },
    keyTakeaway: 'Active retrieval and spaced repetition significantly outperform passive rereading for long-term retention and concept transfer.',
    authorDifficulty: 'Easy',
    editorialStatus: 'Demo Reviewed',
    reviewer: { name: null, role: null },
    references: ['Roediger HL, Karpicke JD. The Power of Testing Memory.', 'Bjork RA. Memory and Metamemory.'],
  },
  {
    id: 'demo-010',
    version: 1,
    contentKind: 'demo',
    exam: 'USMLE Step 1 (Demo Taxonomy)',
    system: 'Demo - Biostatistics & Trial Design',
    discipline: 'Demo - Diagnostic Testing',
    topic: 'Likelihood Ratios & Post-Test Probability',
    learningObjective: 'Differentiate the clinical utility of Likelihood Ratios from Predictive Values in varying disease prevalence settings.',
    vignette: 'A fictional rapid lateral-flow antigen cartridge is evaluated for an endemic viral syndrome. The assay demonstrates a Sensitivity of 90% and a Specificity of 95%.\n\nWhich of the following statements correctly characterizes the Positive Likelihood Ratio (LR+) of this assay and its dependence on population disease prevalence?',
    options: [
      { id: 'A', text: 'The LR+ is 18.0 and remains constant regardless of disease prevalence in the tested population' },
      { id: 'B', text: 'The LR+ is 0.95 and will rise linearly as the disease prevalence increases' },
      { id: 'C', text: 'The LR+ is 0.10 and is only valid when pre-test probability exceeds 50%' },
      { id: 'D', text: 'The LR+ is 1.8 and varies inversely with the positive predictive value' },
      { id: 'E', text: 'The LR+ drops to zero in low-prevalence screening settings' },
    ],
    correctOptionId: 'A',
    explanation: '1) Positive Likelihood Ratio (LR+) = Sensitivity / (1 - Specificity) = 0.90 / (1 - 0.95) = 0.90 / 0.05 = 18.0.\n2) Unlike Positive Predictive Value (PPV), which depends heavily on disease prevalence, Likelihood Ratios are properties derived purely from sensitivity and specificity and do not change with population prevalence.',
    optionExplanations: {
      A: 'Correct. LR+ = Sensitivity / (1 - Specificity) = 0.90 / 0.05 = 18.0. Because sensitivity and specificity are intrinsic assay characteristics, the LR+ remains invariant to prevalence.',
      B: 'Incorrect. 0.95 is the specificity, and LR does not fluctuate with prevalence.',
      C: 'Incorrect. LR- is (1 - Sens) / Spec = 0.10 / 0.95 ≈ 0.105, but this is the negative likelihood ratio, not LR+.',
      D: 'Incorrect. The calculation error misses the denominator (0.05).',
      E: 'Incorrect. The diagnostic power of an LR+ does not collapse in low prevalence; only the resulting post-test probability (PPV) is lower.',
    },
    keyTakeaway: 'Likelihood ratios combine sensitivity and specificity (LR+ = Sens / [1 - Spec]) and do not vary with disease prevalence.',
    authorDifficulty: 'Hard',
    editorialStatus: 'Demo Reviewed',
    reviewer: { name: null, role: null },
    references: ['Sackett DL. Evidence-Based Medicine: How to Practice and Teach EBM.'],
  },
  {
    id: 'demo-011',
    version: 1,
    contentKind: 'demo',
    exam: 'USMLE Step 1 (Demo Taxonomy)',
    system: 'Demo - App Features & Study Workflow',
    discipline: 'Demo - Software Operation',
    topic: 'Tutor Mode vs Timed Mode Mechanics',
    learningObjective: 'Understand how WardWit tracks first-attempt responses and preserves snapshot versions.',
    vignette: 'A student creates a new practice session in WardWit to review flagged biostatistics questions. The student wants immediate feedback after answering each item, with full explanation breakdowns and high-yield key takeaways visible right away. However, they also want their very first choice recorded permanently so that subsequent revisions do not distort their historical accuracy record.\n\nWhich session configuration and software behavior in WardWit provides this experience?',
    options: [
      { id: 'A', text: 'Tutor Mode: displays immediate explanations upon submitting an answer and locks the first submitted answer into the attempt record' },
      { id: 'B', text: 'Timed Mode: reveals explanations instantaneously after each click while keeping a running countdown' },
      { id: 'C', text: 'Simulation Mode: deletes incorrect attempts and increments the question difficulty' },
      { id: 'D', text: 'Flashcard Mode: shuffles options continuously whenever an answer is selected' },
      { id: 'E', text: 'Cloud Mode: synchronizes answers across third-party remote servers in real time' },
    ],
    correctOptionId: 'A',
    explanation: 'In WardWit, Tutor Mode is specifically architected for deliberate practice: feedback and explanations appear immediately after the user submits their choice for that question, and the first submitted answer is permanently saved in the attempt snapshot to protect baseline performance statistics.',
    optionExplanations: {
      A: 'Correct. Tutor Mode delivers immediate learning feedback while locking the first submitted answer to ensure honest analytics.',
      B: 'Incorrect. Timed Mode withholds all feedback until the entire block is submitted or the block deadline expires.',
      C: 'Incorrect. WardWit does not delete attempts or claim to be an official simulation.',
      D: 'Incorrect. Option IDs are stable to preserve review fidelity.',
      E: 'Incorrect. WardWit operates purely on local browser storage (IndexedDB) with zero external cloud servers.',
    },
    keyTakeaway: 'Tutor Mode provides immediate answer feedback while preserving the first-attempt choice for honest scoring.',
    authorDifficulty: 'Easy',
    editorialStatus: 'Demo Reviewed',
    reviewer: { name: null, role: null },
    references: ['WardWit Architecture Guide (Local deliberate practice principles)'],
  },
  {
    id: 'demo-012',
    version: 1,
    contentKind: 'demo',
    exam: 'USMLE Step 1 (Demo Taxonomy)',
    system: 'Demo - App Features & Study Workflow',
    discipline: 'Demo - Data Privacy & Local Storage',
    topic: 'Browser-Only Persistence & Question Snapshots',
    learningObjective: 'Recognize the architectural design of browser-only IndexedDB storage and session version snapshots.',
    vignette: 'A medical student completes an 8-question practice session on their personal laptop using WardWit. The following week, an author updates the wording and explanations of two questions in the local question bank from Version 1 to Version 2. When the student reopens their completed session from the previous week in the Results and Review screen, which behavior occurs?',
    options: [
      { id: 'A', text: 'The completed session displays the exact question snapshots captured at the time the session was created, preventing historical distortion' },
      { id: 'B', text: 'The session is automatically wiped from local memory because its question versions no longer match' },
      { id: 'C', text: 'The student’s past answers are retroactively evaluated against the new Version 2 answer keys' },
      { id: 'D', text: 'A background sync prompt requests cloud authentication to resolve the version difference' },
      { id: 'E', text: 'The session results are converted into an unreadable binary file' },
    ],
    correctOptionId: 'A',
    explanation: 'WardWit study sessions store complete question-version snapshots at the moment of session creation. This domain architecture ensures that subsequent updates or edits to the question bank never mutate past sessions, preserving historical auditability.',
    optionExplanations: {
      A: 'Correct. Question snapshots decouple historical sessions from ongoing question bank updates, guaranteeing that completed blocks reflect the exact content the student saw.',
      B: 'Incorrect. IndexedDB persistence maintains all completed sessions safely.',
      C: 'Incorrect. Past sessions are immutable historical records; they are never re-evaluated against newer versions.',
      D: 'Incorrect. WardWit is an honest, single-device offline application with no cloud authentication.',
      E: 'Incorrect. Sessions remain fully readable and reviewable indefinitely.',
    },
    keyTakeaway: 'Storing question snapshots in study sessions ensures that past results are immutable and immune to subsequent question updates.',
    authorDifficulty: 'Easy',
    editorialStatus: 'Demo Reviewed',
    reviewer: { name: null, role: null },
    references: ['WardWit Architecture Specification (Session Versioning & Persistence)'],
  },
];
